### ISSUE TITLE
I have two questions.

### ISSUE THREAD

**Issue by seonghyun0108** [HaoZhang1018/GANMcC#1]
I owe you for your services.

I have two questions.

1. Why do you share 132 x 132 Data images and 120 x 120 Lable images? Can't you use only one of them?

2. What is the standard for dividing the two?

Thank you.

**Comment by Linfeng-Tang** [comment]
> I owe you for your services.
> 
> I have two questions.
> 
> 1. Why do you share 132 x 132 Data images and 120 x 120 Lable images? Can't you use only one of them?
> 2. What is the standard for dividing the two?
> 
> Thank you.


In fact, the image with a size of 132x132 is actually a padding version of the image with size of 120x120. Because the downsampling caused by the convolution in the generator will bring the boundary information loss, we use the padding version as the input to avoid the boundary information loss. Through this operation, even if there is information loss, it is the invalid boundary information artificially padded.

**Comment by seonghyun0108** [comment]
> > I owe you for your services.
> > I have two questions.
> > 
> > 1. Why do you share 132 x 132 Data images and 120 x 120 Lable images? Can't you use only one of them?
> > 2. What is the standard for dividing the two?
> > 
> > Thank you.
> 
> In fact, the image with a size of 132x132 is actually a padding version of the image with size of 120x120. Because the downsampling caused by the convolution in the generator will bring the boundary information loss, we use the padding version as the input to avoid the boundary information loss. Through this operation, even if there is information loss, it is the invalid boundary information artificially padded.

Thank you for reply.
So do I need padding version image when I want to put in a different size of input?

**Comment by Linfeng-Tang** [comment]
> > > I owe you for your services.
> > > I have two questions.
> > > 
> > > 1. Why do you share 132 x 132 Data images and 120 x 120 Lable images? Can't you use only one of them?
> > > 2. What is the standard for dividing the two?
> > > 
> > > Thank you.
> > 
> > 
> > In fact, the image with a size of 132x132 is actually a padding version of the image with size of 120x120. Because the downsampling caused by the convolution in the generator will bring the boundary information loss, we use the padding version as the input to avoid the boundary information loss. Through this operation, even if there is information loss, it is the invalid boundary information artificially padded.
> 
> Thank you for reply.
> So do I need padding version image when I want to put in a different size of input?

Note that the provided code will automatically perform padding. All you need to do is to put your data in the specified folder, such as "Train_ir/Train_vi" or "Test_ir/Test_vi".
